version: '3.4'
services:
  spark-master:
    image: bde2020/spark-master:2.3.2-hadoop2.8
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
    - 8080:8080
    - 7077:7077
    - 6066:6066
    env_file:
    - conf/bigdata.env
    volumes:
    - ./conf/spark/spark.conf:/spark/conf/spark-defaults.conf
    - ./data:/data
  spark-worker:
    image: quay.io/comp-bio-aging/spark-worker:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
    - 8081:8081
    - 8082:8082
    - 8083:8083
    env_file:
    - conf/bigdata.env
    volumes:
    - ./conf/spark/spark.conf:/spark/conf/spark-defaults.conf
    - ./data:/data
  zeppelin:
    image: quay.io/comp-bio-aging/zeppelin
    env_file:
    - conf/bigdata.env
    ports:
    - 9002:8080
    volumes:
    - ./notebooks/zeppelin:/zeppelin/notebook
    - ./data:/data
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
  db:
    image: postgres:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
    - ./conf/geometa/init/sequencing.sql:/docker-entrypoint-initdb.d/sequencing.sql
    - ./databases/postgres:/data/postgres
    ports:
    - 5432:5432
  adminer:
    image: adminer:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - 5050:8080

networks:
  default:
    driver: overlay
    attachable: true
